### PR TITLE
Patch for wrong localization data for HU, RO and HR

### PR DESCRIPTION
**Pull request by nocive**
Some minor fixes for Hungarian, Croation and Romanian localization data

### CODE REVIEW

**Comment by bojanz** [comment]
Hi, 
You can't modify resources/ because that's the CLDR data, it's automatically generated every time they do a new release. So any change you make wouldn't stick around.

Instead, you should open one or more bug reports in the CLDR trac: http://unicode.org/cldr/trac/
And link them here so I can follow along.

**Comment by nocive** [comment]
Oops, sorry for wasting your time. I actually thought you guys used your own subset of the original CLDR data.

Kind of disappointing that they have these kind of basic mistakes in there.

**Comment by bojanz** [comment]
They have over 200 languages to deal with, mistakes happen.

They do major releases each 6 months, and I've found that each one always brings many fixes, so I'm hoping your report will get addressed quickly as well.

**Comment by bojanz** [comment]
Following up on all CLDR bug reports.

Discussion for HUF fraction digits: http://unicode.org/cldr/trac/ticket/7058
The "lei" symbol for RON was rejected in http://unicode.org/cldr/trac/ticket/8460 (worth adding your feedback).
Found no issue open for the HRK symbol (kuna) or the euro symbols.

**Pull request closed without merging**
